name: Build Docker Image

on:
  push:
    branches:
      - main  # Run workflow on push to main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (No Push)
        run: |
          docker build -t my-nginx-app .
