name: Auto Versioned Docker Build and Push

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Version and Increment
        id: versioning
        run: |
          REPO="${{ secrets.DOCKER_USERNAME }}/my-nginx-app"
          LATEST_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags" | jq -r '.results[].name' | grep -E '^v[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          
          if [[ -z "$LATEST_VERSION" ]]; then
            NEW_VERSION="v1.0"  # First version if no previous version
          else
            MAJOR=$(echo $LATEST_VERSION | cut -d. -f1 | tr -d 'v')
            MINOR=$(echo $LATEST_VERSION | cut -d. -f2)
            NEW_MINOR=$((MINOR + 1))
            NEW_VERSION="v${MAJOR}.${NEW_MINOR}"
          fi

          echo "New Version: $NEW_VERSION"
          echo "IMAGE_TAG=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest
            ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:${{ env.IMAGE_TAG }}

